### ISSUE TITLE
Update app to have latest standard scaffolding

### ISSUE THREAD

**Issue by crandmck** [strongloop-archive/loopback-example-email#3]
This example needs to be updated per https://github.com/strongloop-internal/scrum-loopback/issues/495.

**Comment by jannyHou** [comment]
Hey @crandmck , I have created the pr https://github.com/strongloop/loopback-example-email/pull/4 for this update :)

**Comment by superkhau** [comment]
@crandmck @jannyHou This repo has been archived, do not bother updating.
